spring:
  datasource:
    url: jdbc:h2:~/soccerbatch;DB_CLOSE_ON_EXIT=FALSE
    username: fiap
    password: fiap
  batch:
    jdbc:
      initialize-schema: always

file:
  path: /Users/fabiomiyasato/Downloads/soccer-batch/arquivoparadeletar.txt
